name: "Sync All Logs"
author: Ryan Wilkinson
description: "Sync all log entries from MySQL to BigQuery for the tables defined in config.py"
branding:
  icon: 'arrow-left'
  color: 'orange'
inputs:
  max_days:
    description: "Maximum number of days to sync"
    required: false
    default: "90"
runs:
  using: "composite"
  steps:
