name: Aqualab MySQL to BigQuery Select Test
on:
  workflow_dispatch: # Allow manual trigger of this workflow from the Actions tab
  # schedule:
    # Follows POSIX cron syntax https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07
    # * is a special character in YAML, so must be quoted
    # Run at 09:30 UTC every day which is 03:30 CST/04:30 CDT
    # TODO: Uncomment when we're read to schedule
    #- cron: '30 9 * * *'
jobs:
  Connection_to_VPN:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Install OpenConnect
      run: sudo apt-get update && sudo apt-get install openconnect
    - name: Connect to VPN
      run: echo ${{ secrets.VPN_PASS }} | sudo openconnect --protocol=gp -u ${{ secrets.VPN_USER }} --passwd-on-stdin soe.vpn.wisc.edu &
  Cleanup_Synced_Rows:
    name: Cleanup Synced Rows
    runs-on: ubuntu-22.04
    needs: Connection_to_VPN
    steps:
    - name: Remove old synced events # TODO: figure out/set up key secret for logging in to logger host
      run: |
        mkdir -p ~/.ssh
        echo '${{secrets.FILE_DEPLOY_KEY}}' >> ./key.txt
        chmod 600 ./key.txt
        ssh -o StrictHostKeyChecking=no -i ./key.txt ${{secrets.VPN_USER}}@${{vars.OGD_LOGGER_HOST}} "echo 'connected'"
        ssh -o StrictHostKeyChecking=no -i ./key.txt ${{secrets.VPN_USER}}@${{vars.OGD_LOGGER_HOST}} "mysql -u${{secrets.OGD_ARCHIVING_USER}} -p${{secrets.OGD_ARCHIVING_PASS}} -e 'select count(*) from opengamedata.AQUALAB where synced=1 and datediff(now(), server_time) > 7'"
